title: Kelley Erickson
author: Kelley D. Erickson
email: kerickson22@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 A portfolio of the data science projects I have been working on

# social links
#linkedin: kerickson22
github_username:  kerickson22

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minimal
